services:
  - type: web
    name: sigo-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://sistema-sigo.onrender.com/api
      - key: FORCE_DEPLOY
        value: "2025-10-12-21-00"
      - key: DEBUG_MODE
        value: "true"