services:
  - type: web
    name: sigo-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://sistema-sigo-2025.onrender.com/api
