# Security policy for SIGO project
name: Security Policy

on:
  security_advisory:
  vulnerability_alert:

jobs:
  security-alert:
    name: 🔒 Security Alert
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: 📦 Install dependencies
        run: npm ci
        
      - name: 🔒 Run security audit
        run: npm audit --audit-level=moderate
        
      - name: 📋 Create security issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🔒 Security Vulnerability Detected';
            const body = `
            ## Security Alert
            
            A security vulnerability has been detected in the project dependencies.
            
            **Action Required:**
            1. Review the vulnerability details
            2. Update affected packages
            3. Run tests to ensure compatibility
            4. Deploy fixes to production
            
            **Commands to run:**
            \`\`\`bash
            npm audit
            npm audit fix
            npm run test:run
            \`\`\`
            
            Generated on: ${new Date().toISOString()}
            `;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'high-priority', 'urgent']
            });

