services:
  - type: web
    name: sigo-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://sistema-sigo.onrender.com/api