name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday
  workflow_dispatch: # Manual trigger

jobs:
  check-dependencies:
    name: Check for outdated dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check frontend dependencies
      working-directory: ./sigo-frontend
      run: |
        npm install -g npm-check-updates
        ncu --format table
        ncu --format table --target minor
        
    - name: Check backend dependencies
      working-directory: ./backend
      run: |
        npm install -g npm-check-updates
        ncu --format table
        ncu --format table --target minor